name: CI
on: [pull_request]
jobs:
  eslint:
    name: Lint Code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install

      - name: lint code
        run: yarn nx workspace-lint

      - name: format code
        run: yarn nx format:check
